spring:
  datasource:
    url: jdbc:postgresql//localhost:5432/app-db
    driver-class-name: org.postgresql.Driver
    username: user
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
