spring:
  rabbitmq:
    host: open-data-rabbitmq
    port: 5672
    username : guest
    password : guest

ztt:
  cameras:
    path: /opt/app/data/cameras/
    #path: /home/vtcmer/ztt/dev/docker/docker-basic/test3/open-data/cameras/
  rabbitmq:
    queue: ztt.queue.app.image

