version: '3'
services:
  microservice:
    container_name: c_app_db
    image: img_app_db
    build: .
    ports:
      - "9000:8080"
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=user
      - POSTGRES_DB=app-db
volumes:
  db-data:
    driver: local
