spring:
  rabbitmq:
    host: open-data-rabbitmq
    port: 5672
    username : guest
    password : guest
  data:
    mongodb:
      host: open-data-mongo
      #authentication-database: admin
      database: camera
      #username: root
      #password: 123456
      auto-index-creation: false

ztt:
  cameras:
    path: /opt/app/data/cameras/
    #path: /home/vtcmer/ztt/dev/docker/docker-basic/test3/open-data/cameras/
  rabbitmq:
    queue: ztt.queue.app.db
