version: '3'
services:
  rabbit-od:
    image: "rabbitmq:3-management"
    # hostname: "rabbitvm1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq-od"
  service-extractor:
    container_name: open-data-extractor
    image: img_open_data_extractor
    build: ./open-data-extractor
    depends_on:
      - rabbit-od
  service-image:
    container_name: open-data-image
    image: img_open_data_image
    build: ./app-image
    volumes:
      - ./cameras:/opt/app/data/cameras/
    depends_on:
      - rabbit-od
  service-db:
    container_name: open-data-db
    image: img_open_data_db
    build: ./app-db
    volumes:
      - ./cameras:/opt/app/data/cameras/
    depends_on:
      - mongo_container
      - rabbit-od
  mongo_container:
    image: mongo:latest
   # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:

